version: "3"
services:
  mongo:
    image: mongo:5.0
    volumes:
      - ./volumes/database/:/data/database
    ports:
      - "27017:27017"
  redis:
    image: redis
    volumes:
      - ./volumes/redis/:/data
    ports:
      - "6379:6379"
  api:
    restart: always
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
