name: Test Nodejs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.x
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: docker --version
      - run: docker-compose --version
